### ISSUE TITLE
Be explicit about Scope

### ISSUE THREAD

**Issue by OzHache** [Jonathan-Blazeby/HammerFall#1]
https://github.com/Jonathan-Blazeby/HammerFall/blob/9fb771e62cfe16c16e6c10468c0a8e6640c4ad01/Assets/GravityManager.cs#L7

While C# does take the assumption that all fields in a class will be private, it is better form to be explicit about it.

**Comment by Jonathan-Blazeby** [comment]
Thanks, generally I remember to add Private to my fields, but must have missed that one. Issue has been fixed.
