### ISSUE TITLE
Don't ask for all the anything. 

### ISSUE THREAD

**Issue by OzHache** [Jonathan-Blazeby/HammerFall#10]
https://github.com/Jonathan-Blazeby/HammerFall/blob/9fb771e62cfe16c16e6c10468c0a8e6640c4ad01/Assets/GravityManager.cs#L28-L33

Have the scripts that need to register, register on Awake, Getting all the Monobehaviours is an awful way to do this.

**Comment by Jonathan-Blazeby** [comment]
Replaced with awake functions in MovementManager calling the GravityManager static instance.

**Comment by Jonathan-Blazeby** [comment]
Race condition issues happening with the awake methods
