### ISSUE TITLE
Question on this code.

### ISSUE THREAD

**Issue by OzHache** [Jonathan-Blazeby/HammerFall#2]
https://github.com/Jonathan-Blazeby/HammerFall/blob/9fb771e62cfe16c16e6c10468c0a8e6640c4ad01/Assets/Camera_Scripts/CameraHandler.cs#L13

It feels like this line of code is here solely to solve a weird issue. If the position of the camera is to be adjusted on start to a fixed position. Why not set that position in the inspector?

**Comment by Jonathan-Blazeby** [comment]
Fair point. I've scrapped it, but I've kept some functionality in there for remembering the offsets, as I still need to add some extra code to prevent the camera clipping through walls.
