### ISSUE TITLE
Dedicated Initialization functions

### ISSUE THREAD

**Issue by OzHache** [Jonathan-Blazeby/HammerFall#3]
https://github.com/Jonathan-Blazeby/HammerFall/blob/9fb771e62cfe16c16e6c10468c0a8e6640c4ad01/Assets/Character_Scripts/AttackManager.cs#L18-L19
You should consider moving this to an initialization function in here. The Monobehavious should call on actions to be performed they should contain as little code as possible that way your method names will take the place of good comments.

**Comment by Jonathan-Blazeby** [comment]
Went through all scripts and moved code blocks out of Start() & Update(), and into various functions.
