### ISSUE TITLE
Magic Numbers. 

### ISSUE THREAD

**Issue by OzHache** [Jonathan-Blazeby/HammerFall#5]
https://github.com/Jonathan-Blazeby/HammerFall/blob/9fb771e62cfe16c16e6c10468c0a8e6640c4ad01/Assets/Character_Scripts/MovementManager.cs#L80-L98

Magic numbers are the numbers we use when trying something out to see if we can get it to work, why does it work? Who knows, it just does. 

Convert those magic numbers into constants with meaningful names.

**Comment by Jonathan-Blazeby** [comment]
Converted into magic numbers 0.95f, 0.25f, and 8, into constants groundCheckPointAdjust, groundCheckSphereDistAjust, and traversableLayer.
